parameters:
  kbrw.content.type.normalizer.class: "Kbrw\RiakBundle\Service\Content\ContentTypeNormalizer"
  kbrw.content.type.normalizer.types:
    "application/xml": [xml, xsd, xslt]
    "application/json": [json]
    "text/plain": [txt]

  kbrw.guzzle.client.provider.class: "Kbrw\RiakBundle\Service\WebserviceClient\Guzzle\SimpleGuzzleClientProvider"

  kbrw.riak.cluster.class: "Kbrw\RiakBundle\Service\WebserviceClient\Riak\RiakClusterServiceClient"
  kbrw.riak.cluster.route: "{protocol}://{domain}:{port}/riak/{?buckets}"

  kbrw.riak.bucket.class: "Kbrw\RiakBundle\Service\WebserviceClient\Riak\RiakBucketServiceClient"
  kbrw.riak.bucket.route: "{protocol}://{domain}:{port}/riak/{bucket}{?keys,props}"

  kbrw.riak.kv.class: "Kbrw\RiakBundle\Service\WebserviceClient\Riak\RiakKVServiceClient"
  kbrw.riak.kv.route: "{protocol}://{domain}:{port}/riak/{bucket}/{id}{?r,w,dw}"

  kbrw.riak.search.class: "Kbrw\RiakBundle\Service\WebserviceClient\Riak\RiakSearchServiceClient"
  kbrw.riak.search.route: "{protocol}://{domain}:{port}/solr/{bucket}/select{?q,start,rows,df,q.op,sort,wt,filter,fl}"

  kbrw.riak.mapreduce.class: "Kbrw\RiakBundle\Service\WebserviceClient\Riak\RiakMapReduceServiceClient"
  kbrw.riak.mapreduce.route: "{protocol}://{domain}:{port}/mapred"

  kbrw.riak.status.class: "Kbrw\RiakBundle\Service\WebserviceClient\Riak\RiakStatusServiceClient"
  kbrw.riak.status.route: "{protocol}://{domain}:{port}/stats"

services:
  kbrw.content.type.normalizer:
    class: "%kbrw.content.type.normalizer.class%"
    arguments: [%kbrw.content.type.normalizer.types%]

  kbrw.guzzle.client.provider:
    class: "%kbrw.guzzle.client.provider.class%"

  kbrw.riak.cluster:
    class: "%kbrw.riak.cluster.class%"
    calls:
      - [setRoute,                 [ "%kbrw.riak.cluster.route%" ] ]
      - [setLogger,                [ "@logger" ] ]
      - [setSerializer,            [ "@jms_serializer" ] ]

  kbrw.riak.bucket:
    class: "%kbrw.riak.bucket.class%"
    calls:
      - [setRoute,                 [ "%kbrw.riak.bucket.route%" ] ]
      - [setLogger,                [ "@logger" ] ]
      - [setSerializer,            [ "@jms_serializer" ] ]

  kbrw.riak.kv:
    class: "%kbrw.riak.kv.class%"
    calls:
      - [setRoute,                 [ "%kbrw.riak.kv.route%" ] ]
      - [setLogger,                [ "@logger" ] ]
      - [setContentTypeNormalizer, [ "@kbrw.content.type.normalizer" ] ]
      - [setSerializer,            [ "@jms_serializer" ] ]

  kbrw.riak.search:
    class: "%kbrw.riak.search.class%"
    calls:
      - [setRoute,                 [ "%kbrw.riak.search.route%" ] ]
      - [setLogger,                [ "@logger" ] ]
      - [setSerializer,            [ "@jms_serializer" ] ]

  kbrw.riak.mapreduce:
    class: "%kbrw.riak.mapreduce.class%"
    calls:
      - [setRoute,                 [ "%kbrw.riak.mapreduce.route%" ] ]
      - [setLogger,                [ "@logger" ] ]
      - [setSerializer,            [ "@jms_serializer" ] ]

  kbrw.riak.status:
    class: "%kbrw.riak.status.class%"
    calls:
      - [setRoute,                 [ "%kbrw.riak.status.route%" ] ]
      - [setLogger,                [ "@logger" ] ]
      - [setSerializer,            [ "@jms_serializer" ] ]
