language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev

script: ./bin/phpunit --coverage-clover clover

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php
